# Air configuration for UTOL API REST example
# This file enables hot reloading for the api_rest example

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "cd api_rest && go build -o ../tmp/main ."
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary.
full_bin = "cd api_rest && ../tmp/main serve"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git", "node_modules", "api_rest/tmp"]
# Watch these directories if you specified.
include_dir = ["api_rest"]
# Exclude files.
exclude_file = []
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_root = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = "0.5s"

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true 