name: fxConfig Test

on:
  pull_request:
    branches: [ main ]
    paths: [ 'fxConfig/**', '.github/workflows/fxconfig-test.yml' ]
  push:
    branches: [ main ]
    paths: [ 'fxConfig/**', '.github/workflows/fxconfig-test.yml' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Verify dependencies
      run: go mod verify

    - name: Download dependencies
      run: go mod download

    - name: Run tests for fxConfig module
      run: go test -v ./fxConfig/...

    - name: Run go vet on fxConfig
      run: go vet ./fxConfig/...

    - name: Run go fmt check on fxConfig
      run: |
        if [ "$(gofmt -s -l ./fxConfig/ | wc -l)" -gt 0 ]; then
          echo "The following fxConfig files are not formatted correctly:"
          gofmt -s -l ./fxConfig/
          exit 1
        fi

    - name: Run go mod tidy check
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go.mod or go.sum is not tidy. Please run 'go mod tidy' and commit changes."
          git diff
          exit 1
        fi 