name: fxEcho Release

on:
  push:
    branches: [ main ]
    paths: [ 'fxEcho/**', '.github/workflows/fxecho-release.yml' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Verify dependencies
      run: go mod verify

    - name: Download dependencies
      run: go mod download

    - name: Run tests for fxEcho
      run: go test -v ./fxEcho/...

    - name: Run go vet on fxEcho
      run: go vet ./fxEcho/...

    - name: Determine next fxEcho version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # tag-prefix: "fxecho-v"
        bump-each-commit: false
        search-commit-body: false
        include-prereleases: false

    - name: Create fxEcho tag
      run: |
        git tag ${{ steps.semver.outputs.version }}
        git push origin ${{ steps.semver.outputs.version }}

    - name: Create fxEcho Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.version }}
        release_name: fxEcho Release ${{ steps.semver.outputs.version }}
        body: |
          ## fxEcho Changes in ${{ steps.semver.outputs.version }}
          
          This release includes updates to the fxEcho module:
          - Echo web framework integration with Uber's fx
          - Dependency injection ready architecture
          - Modular design for easy extension
          
          ### Version Type: ${{ steps.semver.outputs.version-type }}
          ### Previous Version: ${{ steps.semver.outputs.previous-version }}
          
          ### Commit History (fxEcho only)
          $(git log --pretty=format:"- %s" $(git describe --tags --match "fxecho-*" --abbrev=0 2>/dev/null || echo "")..HEAD -- fxEcho/)
        draft: false
        prerelease: false

    - name: Publish fxEcho to Go Package Registry
      run: |
        echo "fxEcho module published to Go package registry"
        echo "Available at: github.com/UTOL-s/module/fxEcho@${{ steps.semver.outputs.version }}" 