name: fxGorm Release

on:
  push:
    branches: [ fxGorm ]
    paths: [ 'fxGorm/**', '.github/workflows/fxgorm-release.yml' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Verify dependencies
      run: go mod verify

    - name: Download dependencies
      run: go mod download

    - name: Run tests for fxGorm
      run: go test -v ./fxGorm/...

    - name: Run go vet on fxGorm
      run: go vet ./fxGorm/...

    - name: Determine next fxGorm version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prefix: "fxgorm-"
        branch: fxGorm
        skipInvalidTags: true

    - name: Generate release notes
      id: release_notes
      run: |
        PREVIOUS_TAG=$(git describe --tags --match "fxgorm-*" --abbrev=0 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          COMMIT_HISTORY=$(git log --pretty=format:"- %s" -- fxGorm/)
        else
          COMMIT_HISTORY=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD -- fxGorm/)
        fi
        echo "commit_history<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMIT_HISTORY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create tag
      id: tag
      run: |
        NEW_TAG=${{ steps.semver.outputs.next }}
        echo "Creating new tag: $NEW_TAG"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git tag -a $NEW_TAG -m "chore(release): $NEW_TAG"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/UTOL-s/module.git
        git push origin $NEW_TAG
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Create fxGorm Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.semver.outputs.next }}
        name: fxGorm Release ${{ steps.semver.outputs.next }}
        body: |
          ## fxGorm Changes in ${{ steps.semver.outputs.next }}
          
          This release includes updates to the fxGorm module:
          - Dynamic GORM configuration and connection pooling
          - Multi-database support (Postgres, MySQL, SQLite, SQL Server)
          - Modular, maintainable code structure
          - Dependency injection ready
          
          ### Version Type: ${{ steps.semver.outputs.version-type }}
          ### Previous Version: ${{ steps.semver.outputs.previous-version }}
          
          ### Commit History (fxGorm only)
          ${{ steps.release_notes.outputs.commit_history }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish fxGorm to Go Package Registry
      run: |
        echo "fxGorm module published to Go package registry"
        echo "Available at: github.com/UTOL-s/module/fxGorm@${{ steps.semver.outputs.next }}" 