name: Module Release

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'fxConfig/**', 'fxEcho/**' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Verify dependencies
      run: go mod verify

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Determine next version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag-prefix: "v"
        bump-each-commit: false
        search-commit-body: false
        include-prereleases: false

    - name: Create module tag
      run: |
        git tag ${{ steps.semver.outputs.version }}
        git push origin ${{ steps.semver.outputs.version }}

    - name: Create Module Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.version }}
        release_name: Module Release ${{ steps.semver.outputs.version }}
        body: |
          ## Module Changes in ${{ steps.semver.outputs.version }}
          
          This release includes updates to the UTOL module:
          - Overall module structure improvements
          - Documentation updates
          - CI/CD workflow enhancements
          
          ### Version Type: ${{ steps.semver.outputs.version-type }}
          ### Previous Version: ${{ steps.semver.outputs.previous-version }}
          
          ### Commit History (module-wide changes only)
          $(git log --pretty=format:"- %s" $(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "")..HEAD -- . ':!fxConfig' ':!fxEcho')
        draft: false
        prerelease: false

    - name: Publish Module to Go Package Registry
      run: |
        echo "Module published to Go package registry"
        echo "Available at: github.com/UTOL-s/module@${{ steps.semver.outputs.version }}" 