name: Module Release

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'fxConfig/**', 'fxEcho/**' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Verify dependencies
      run: go mod verify

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Determine next version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prefix: "v"
        branch: main
        skipInvalidTags: true

    - name: Generate release notes
      id: release_notes
      run: |
        PREVIOUS_TAG=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          COMMIT_HISTORY=$(git log --pretty=format:"- %s" -- . ':!fxConfig' ':!fxEcho')
        else
          COMMIT_HISTORY=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD -- . ':!fxConfig' ':!fxEcho')
        fi
        echo "commit_history<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMIT_HISTORY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create module tag
      id: tag
      run: |
        NEW_TAG=${{ steps.semver.outputs.next }}
        echo "Creating new tag: $NEW_TAG"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git tag -a $NEW_TAG -m "chore(release): $NEW_TAG"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/UTOL-s/module.git
        git push origin $NEW_TAG
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Create Module Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.semver.outputs.next }}
        name: Module Release ${{ steps.semver.outputs.next }}
        body: |
          ## Module Changes in ${{ steps.semver.outputs.next }}
          
          This release includes updates to the UTOL module:
          - Overall module structure improvements
          - Documentation updates
          - CI/CD workflow enhancements
          
          ### Version Type: ${{ steps.semver.outputs.version-type }}
          ### Previous Version: ${{ steps.semver.outputs.previous-version }}
          
          ### Commit History (module-wide changes only)
          ${{ steps.release_notes.outputs.commit_history }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Module to Go Package Registry
      run: |
        echo "Module published to Go package registry"
        echo "Available at: github.com/UTOL-s/module@${{ steps.semver.outputs.next }}" 